function w1 = connectionWeight1(s, d, u, i, j, k, l)
  w1 = u(3)*kroneckerDelta(j, k) + u(3)*kroneckerDelta(l, i) ...
       - u(3)*kroneckerDelta(i, k) - u(3)*kroneckerDelta(j, l) ...
       + u(4)*kroneckerDelta(i, k)*kroneckerDelta(j, l) ...
       - u(5)/2 * kroneckerDelta(j, k) * kroneckerDelta(i, l) ...
       - u(6)*kroneckerDelta(i, k)*kroneckerDelta(j, l) ...
       - u(7)*kroneckerDelta(i, k)*kroneckerDelta(j, l) ...
       - u(8)*kroneckerDelta(i, k)*kroneckerDelta(j, l);